######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 23:26:04 2013
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += msplans client trindex \
    tqservice jira \
    tqplugapi

msplans.depends = client

CONFIG += ordered


TARGET = traquera
