#ifndef TQAXFACTORY_GLOBAL_H
#define TQAXFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TQAXFACTORY_LIBRARY)
#  define TQAXFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TQAXFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TQAXFACTORY_GLOBAL_H
