######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 16:38:33 2013
######################################################################

QT += sql

TEMPLATE = lib
TARGET = trklib
DEPENDPATH += .
INCLUDEPATH += . \
    ..\trktool\lib    


# Input
HEADERS += tracker.h trdefs.h trktool2.h trkview.h ttutils.h ttglobal.h settings.h
SOURCES += tracker.cpp trkview.cpp ttutils.cpp ttglonal.cpp settings.cpp
